export type CrewLocationSeed = {
  id: string;
  initials: string;
  displayName: string;
  city: string;
  state: string;
  country: string;
  locationLabel: string;
  publicGlobeLabel: string;
  aircraftExperienceSummary: string;
  totalTime: string;
  needsLocationReview: boolean;
  hasUsableLocation: boolean;
  geocodeStatus: "needs_geocoding" | "location_review_needed" | "geocoded";
};

// Source: Pilot Network (MASTER).xlsx / All Pilots tab.
// Public-safe: does not include email, phone, or street address.
// Next step before 3D globe: map city/state to base airport or lat/lng.
export const crewLocationSeeds: CrewLocationSeed[] = [
  {
    "id": "crew-001-tb",
    "initials": "TB",
    "displayName": "Timothy B.",
    "city": "Grand Rapids",
    "state": "MI",
    "country": "USA",
    "locationLabel": "Grand Rapids, MI",
    "publicGlobeLabel": "Grand Rapids, MI · Crew Coverage",
    "aircraftExperienceSummary": "Gulfstream, G-IV, ERJ, Helicopter",
    "totalTime": "21870.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-002-sj",
    "initials": "SJ",
    "displayName": "Stan J.",
    "city": "Castle Rock",
    "state": "CO",
    "country": "USA",
    "locationLabel": "Castle Rock, CO",
    "publicGlobeLabel": "Castle Rock, CO · Crew Coverage",
    "aircraftExperienceSummary": "CE560, CE560XL, XLS",
    "totalTime": "7112.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-003-rt",
    "initials": "RT",
    "displayName": "Richard T.",
    "city": "San Diego",
    "state": "CA",
    "country": "USA",
    "locationLabel": "San Diego, CA",
    "publicGlobeLabel": "San Diego, CA · Crew Coverage",
    "aircraftExperienceSummary": "A320",
    "totalTime": "",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-004-rh",
    "initials": "RH",
    "displayName": "Robert H.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "CE560, CE-560, CE-680, CE-500, Lear, Gulfstream",
    "totalTime": "6480.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-005-ph",
    "initials": "PH",
    "displayName": "Paul H.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "LR45, LR75, Falcon, DA-EASy, G200, A320",
    "totalTime": "14061.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-006-ds",
    "initials": "DS",
    "displayName": "David S.",
    "city": "Wilton",
    "state": "NH",
    "country": "USA",
    "locationLabel": "Wilton, NH",
    "publicGlobeLabel": "Wilton, NH · Crew Coverage",
    "aircraftExperienceSummary": "CE-500, CE-525, CE525, Lear, Hawker, Cessna",
    "totalTime": "10682.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-007-ch",
    "initials": "CH",
    "displayName": "Christin H.",
    "city": "Ypsilanti",
    "state": "MI",
    "country": "USA",
    "locationLabel": "Ypsilanti, MI",
    "publicGlobeLabel": "Ypsilanti, MI · Crew Coverage",
    "aircraftExperienceSummary": "LR-45, CL-65, Avanti, Piaggio, P-180",
    "totalTime": "4240.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-008-rh",
    "initials": "RH",
    "displayName": "Robert H.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "Gulfstream, Challenger",
    "totalTime": "4076.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-009-as",
    "initials": "AS",
    "displayName": "Alen S.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "Learjet, Lear",
    "totalTime": "2088.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-010-rm",
    "initials": "RM",
    "displayName": "Ryan M.",
    "city": "Orlando",
    "state": "FL",
    "country": "USA",
    "locationLabel": "Orlando, FL",
    "publicGlobeLabel": "Orlando, FL · Crew Coverage",
    "aircraftExperienceSummary": "Avanti, Piaggio",
    "totalTime": "1605.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-011-cs",
    "initials": "CS",
    "displayName": "Christopher S.",
    "city": "Kirkwood",
    "state": "MO",
    "country": "USA",
    "locationLabel": "Kirkwood, MO",
    "publicGlobeLabel": "Kirkwood, MO · Crew Coverage",
    "aircraftExperienceSummary": "CE-525, CE-525S, Citation CJ4, CJ4, G200, HondaJet",
    "totalTime": "1875.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-012-mh",
    "initials": "MH",
    "displayName": "M. H.",
    "city": "West Fork",
    "state": "AR",
    "country": "USA",
    "locationLabel": "West Fork, AR",
    "publicGlobeLabel": "West Fork, AR · Crew Coverage",
    "aircraftExperienceSummary": "CE560, CE560XL, XLS, PC-12, Pilatus PC-12, Learjet",
    "totalTime": "",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-013-mb",
    "initials": "MB",
    "displayName": "Michael B.",
    "city": "Allentown",
    "state": "PA",
    "country": "USA",
    "locationLabel": "Allentown, PA",
    "publicGlobeLabel": "Allentown, PA · Crew Coverage",
    "aircraftExperienceSummary": "Learjet, Lear",
    "totalTime": "1421.6",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-014-mc",
    "initials": "MC",
    "displayName": "Malcolm C.",
    "city": "Waterloo",
    "state": "IA",
    "country": "USA",
    "locationLabel": "Waterloo, IA",
    "publicGlobeLabel": "Waterloo, IA · Crew Coverage",
    "aircraftExperienceSummary": "",
    "totalTime": "",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-015-tm",
    "initials": "TM",
    "displayName": "Thomas M.",
    "city": "Cape Coral",
    "state": "FL",
    "country": "USA",
    "locationLabel": "Cape Coral, FL",
    "publicGlobeLabel": "Cape Coral, FL · Crew Coverage",
    "aircraftExperienceSummary": "CE560, CE-560, CE560XL, CE-560XL, CE 680, CE-680",
    "totalTime": "27231.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-016-ji",
    "initials": "JI",
    "displayName": "Joshua I.",
    "city": "Punta Gorda",
    "state": "FL",
    "country": "USA",
    "locationLabel": "Punta Gorda, FL",
    "publicGlobeLabel": "Punta Gorda, FL · Crew Coverage",
    "aircraftExperienceSummary": "PC-12",
    "totalTime": "7200.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-017-jc",
    "initials": "JC",
    "displayName": "Jason C.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "CE-525, CE-525S, King Air, Bell, Helicopter, Rotorcraft",
    "totalTime": "7150.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-018-eh",
    "initials": "EH",
    "displayName": "Edward H.",
    "city": "Deerfield",
    "state": "NH",
    "country": "USA",
    "locationLabel": "Deerfield, NH",
    "publicGlobeLabel": "Deerfield, NH · Crew Coverage",
    "aircraftExperienceSummary": "Bonanza, Piper, Cessna, Cessna 172, Baron, Robinson",
    "totalTime": "6627.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-019-em",
    "initials": "EM",
    "displayName": "EDWARD M.",
    "city": "Belleair Beach",
    "state": "FL",
    "country": "USA",
    "locationLabel": "Belleair Beach, FL",
    "publicGlobeLabel": "Belleair Beach, FL · Crew Coverage",
    "aircraftExperienceSummary": "King Air, King Air 350, KA 350, PC-12, Pilatus PC-12, Lear",
    "totalTime": "5000.0",
    "needsLocationReview": true,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-020-ts",
    "initials": "TS",
    "displayName": "Thomas S.",
    "city": "Hilton Head",
    "state": "SC",
    "country": "USA",
    "locationLabel": "Hilton Head, SC",
    "publicGlobeLabel": "Hilton Head, SC · Crew Coverage",
    "aircraftExperienceSummary": "Cessna",
    "totalTime": "5000.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-021-cp",
    "initials": "CP",
    "displayName": "Christine P.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "C-17, Citation 560, XLS, XLS+, King Air, Cessna",
    "totalTime": "2925.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-022-js",
    "initials": "JS",
    "displayName": "Justin S.",
    "city": "Pittsburgh",
    "state": "PA",
    "country": "USA",
    "locationLabel": "Pittsburgh, PA",
    "publicGlobeLabel": "Pittsburgh, PA · Crew Coverage",
    "aircraftExperienceSummary": "Cirrus, Piper, Seminole, Bell",
    "totalTime": "2423.5",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-023-dh",
    "initials": "DH",
    "displayName": "Devon H.",
    "city": "Yukon",
    "state": "OK",
    "country": "USA",
    "locationLabel": "Yukon, OK",
    "publicGlobeLabel": "Yukon, OK · Crew Coverage",
    "aircraftExperienceSummary": "CE-560, CE-560XL, CE-680, PA-46",
    "totalTime": "2389.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-024-dh",
    "initials": "DH",
    "displayName": "Deepali H.",
    "city": "Fargo",
    "state": "ND",
    "country": "USA",
    "locationLabel": "Fargo, ND",
    "publicGlobeLabel": "Fargo, ND · Crew Coverage",
    "aircraftExperienceSummary": "King Air, King Air 350, Lear, B737, Caravan",
    "totalTime": "2056.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-025-cj",
    "initials": "CJ",
    "displayName": "Cecil J.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "CE560, CE-560, CE560XL, CE-560XL, Citation 560, XLS",
    "totalTime": "2023.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-026-sd",
    "initials": "SD",
    "displayName": "Susanne D.",
    "city": "Cypress",
    "state": "TX",
    "country": "USA",
    "locationLabel": "Cypress, TX",
    "publicGlobeLabel": "Cypress, TX · Crew Coverage",
    "aircraftExperienceSummary": "Cessna, Cessna 172",
    "totalTime": "1960.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-027-kb",
    "initials": "KB",
    "displayName": "Kyle B.",
    "city": "O'Fallon",
    "state": "IL",
    "country": "USA",
    "locationLabel": "O'Fallon, IL",
    "publicGlobeLabel": "O'Fallon, IL · Crew Coverage",
    "aircraftExperienceSummary": "C-17, KC-135, KC-46",
    "totalTime": "1825.0",
    "needsLocationReview": true,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-028-ab",
    "initials": "AB",
    "displayName": "Amolk B.",
    "city": "Lake Forest",
    "state": "CA",
    "country": "USA",
    "locationLabel": "Lake Forest, CA",
    "publicGlobeLabel": "Lake Forest, CA · Crew Coverage",
    "aircraftExperienceSummary": "Embraer 145, Piper, Cessna, Cessna 172, PA-28, Tecnam P2006T",
    "totalTime": "1814.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-029-kg",
    "initials": "KG",
    "displayName": "Kerolos G.",
    "city": "Sterling",
    "state": "VA",
    "country": "USA",
    "locationLabel": "Sterling, VA",
    "publicGlobeLabel": "Sterling, VA · Crew Coverage",
    "aircraftExperienceSummary": "Lear, ERJ",
    "totalTime": "1800.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-030-kw",
    "initials": "KW",
    "displayName": "Kevin W.",
    "city": "Spring",
    "state": "TX",
    "country": "USA",
    "locationLabel": "Spring, TX",
    "publicGlobeLabel": "Spring, TX · Crew Coverage",
    "aircraftExperienceSummary": "",
    "totalTime": "1778.0",
    "needsLocationReview": true,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-031-ak",
    "initials": "AK",
    "displayName": "Ali K.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "Piper, Cessna",
    "totalTime": "1515.0",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-032-mw",
    "initials": "MW",
    "displayName": "Matthew W.",
    "city": "Tempe",
    "state": "AZ",
    "country": "USA",
    "locationLabel": "Tempe, AZ",
    "publicGlobeLabel": "Tempe, AZ · Crew Coverage",
    "aircraftExperienceSummary": "",
    "totalTime": "1275.0",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-033-jw",
    "initials": "JW",
    "displayName": "Jacob W.",
    "city": "Central Point",
    "state": "OR",
    "country": "USA",
    "locationLabel": "Central Point, OR",
    "publicGlobeLabel": "Central Point, OR · Crew Coverage",
    "aircraftExperienceSummary": "C172, C182, PA-28",
    "totalTime": "1052.0",
    "needsLocationReview": true,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-034-be",
    "initials": "BE",
    "displayName": "Brian E.",
    "city": "",
    "state": "",
    "country": "USA",
    "locationLabel": "",
    "publicGlobeLabel": "Location review needed · Crew Coverage",
    "aircraftExperienceSummary": "King Air, Lear, Gulfstream, G-IV, G-V, B-737",
    "totalTime": "",
    "needsLocationReview": true,
    "hasUsableLocation": false,
    "geocodeStatus": "location_review_needed"
  },
  {
    "id": "crew-035-sl",
    "initials": "SL",
    "displayName": "Skeeter L.",
    "city": "DeLand",
    "state": "FL",
    "country": "USA",
    "locationLabel": "DeLand, FL",
    "publicGlobeLabel": "DeLand, FL · Crew Coverage",
    "aircraftExperienceSummary": "King Air, Cessna",
    "totalTime": "",
    "needsLocationReview": true,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-036-da",
    "initials": "DA",
    "displayName": "Daryoosh A.",
    "city": "Princeton",
    "state": "TX",
    "country": "USA",
    "locationLabel": "Princeton, TX",
    "publicGlobeLabel": "Princeton, TX · Crew Coverage",
    "aircraftExperienceSummary": "",
    "totalTime": "",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-037-sp",
    "initials": "SP",
    "displayName": "Stephen P.",
    "city": "Kenner",
    "state": "LA",
    "country": "USA",
    "locationLabel": "Kenner, LA",
    "publicGlobeLabel": "Kenner, LA · Crew Coverage",
    "aircraftExperienceSummary": "King Air, Piper, Seneca, Navajo, Bell",
    "totalTime": "",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-038-vk",
    "initials": "VK",
    "displayName": "Victor K.",
    "city": "Dallas",
    "state": "TX",
    "country": "USA",
    "locationLabel": "Dallas, TX",
    "publicGlobeLabel": "Dallas, TX · Crew Coverage",
    "aircraftExperienceSummary": "B737, Bonanza, Baron",
    "totalTime": "",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  },
  {
    "id": "crew-039-tm",
    "initials": "TM",
    "displayName": "Timothy M.",
    "city": "Walhonding",
    "state": "OH",
    "country": "USA",
    "locationLabel": "Walhonding, OH",
    "publicGlobeLabel": "Walhonding, OH · Crew Coverage",
    "aircraftExperienceSummary": "Lear",
    "totalTime": "",
    "needsLocationReview": false,
    "hasUsableLocation": true,
    "geocodeStatus": "needs_geocoding"
  }
];
