export type CrewLocationSeed = {
  id: string;
  publicLabel: string;
  city: string;
  state?: string;
  country: string;
  region?: string;
  baseAirport?: string;
  lat?: number;
  lng?: number;
  aircraftExperience?: string[];
  role?: string;
};

export const CREW_LOCATION_SEEDS: CrewLocationSeed[] = [
  {
    id: "south-florida-light-jet",
    publicLabel: "South Florida · Light Jet Crew",
    city: "Fort Lauderdale",
    state: "FL",
    country: "United States",
    region: "South Florida",
    baseAirport: "KFLL",
    lat: 26.0726,
    lng: -80.1527,
    aircraftExperience: ["Citation", "Phenom", "Light Jet"],
    role: "Contract Pilot Coverage",
  },
  {
    id: "kpmp-contract-pilot",
    publicLabel: "KPMP · Contract Pilot Coverage",
    city: "Pompano Beach",
    state: "FL",
    country: "United States",
    region: "South Florida",
    baseAirport: "KPMP",
    lat: 26.2471,
    lng: -80.1111,
    aircraftExperience: ["Piston", "Turboprop", "Light Jet"],
    role: "Contract Pilot Coverage",
  },
  {
    id: "fort-lauderdale-citation",
    publicLabel: "Fort Lauderdale · Citation Experience",
    city: "Fort Lauderdale",
    state: "FL",
    country: "United States",
    region: "South Florida",
    baseAirport: "KFXE",
    lat: 26.1973,
    lng: -80.1707,
    aircraftExperience: ["Citation", "Light Jet"],
    role: "Jet Crew Support",
  },
  {
    id: "northeast-jet-support",
    publicLabel: "Northeast · Jet Crew Support",
    city: "Teterboro",
    state: "NJ",
    country: "United States",
    region: "Northeast",
    baseAirport: "KTEB",
    lat: 40.8501,
    lng: -74.0608,
    aircraftExperience: ["Light Jet", "Midsize Jet", "Large Cabin"],
    role: "Jet Crew Support",
  },
  {
    id: "texas-crew-coverage",
    publicLabel: "Texas · Crew Coverage",
    city: "Dallas",
    state: "TX",
    country: "United States",
    region: "Texas",
    baseAirport: "KDAL",
    lat: 32.8471,
    lng: -96.8518,
    aircraftExperience: ["Turboprop", "Midsize Jet", "Super-Midsize Jet"],
    role: "Crew Coverage",
  },
  {
    id: "west-coast-contract-network",
    publicLabel: "West Coast · Contract Pilot Network",
    city: "Van Nuys",
    state: "CA",
    country: "United States",
    region: "West Coast",
    baseAirport: "KVNY",
    lat: 34.2098,
    lng: -118.4899,
    aircraftExperience: ["Light Jet", "Midsize Jet", "Large Cabin"],
    role: "Contract Pilot Network",
  },
  {
    id: "southeast-turboprop",
    publicLabel: "Southeast · Turboprop Coverage",
    city: "Atlanta",
    state: "GA",
    country: "United States",
    region: "Southeast",
    baseAirport: "KPDK",
    lat: 33.8756,
    lng: -84.302,
    aircraftExperience: ["King Air", "Pilatus PC-12", "Turboprop"],
    role: "Crew Coverage",
  },
  {
    id: "mountain-west-maintenance",
    publicLabel: "Mountain West · Maintenance Repositioning",
    city: "Denver",
    state: "CO",
    country: "United States",
    region: "Mountain West",
    baseAirport: "KAPA",
    lat: 39.5701,
    lng: -104.8493,
    aircraftExperience: ["Turboprop", "Light Jet", "Midsize Jet"],
    role: "Maintenance Repositioning",
  },
  {
    id: "midwest-assignment-review",
    publicLabel: "Midwest · Assignment Review",
    city: "Chicago",
    state: "IL",
    country: "United States",
    region: "Midwest",
    baseAirport: "KPWK",
    lat: 42.1143,
    lng: -87.9015,
    aircraftExperience: ["Piston", "Turboprop", "Jet"],
    role: "Assignment Review",
  },
  {
    id: "southwest-jet-crew",
    publicLabel: "Southwest · Jet Crew Support",
    city: "Scottsdale",
    state: "AZ",
    country: "United States",
    region: "Southwest",
    baseAirport: "KSDL",
    lat: 33.6229,
    lng: -111.9105,
    aircraftExperience: ["Light Jet", "Midsize Jet"],
    role: "Jet Crew Support",
  },
];

export const CREW_LOCATION_NEEDS_REVIEW: CrewLocationSeed[] = [];
