import type { GlobeMarker } from "@/components/ui/3d-globe";

export type CrewAirportCoverageMarker = GlobeMarker & {
  airportCode: string;
  airportName: string;
  sourceLocation: string;
  crewCount: number;
};

const CREW_MARKER_SRC = "/images/amg-crew-marker.svg";

export const crewAirportGlobeMarkers: CrewAirportCoverageMarker[] = [
  {
    lat: 42.8808,
    lng: -85.5228,
    src: CREW_MARKER_SRC,
    label: "KGRR · Grand Rapids Crew Coverage",
    airportCode: "KGRR",
    airportName: "Gerald R. Ford International Airport",
    sourceLocation: "Grand Rapids, MI",
    crewCount: 1,
  },
  {
    lat: 39.5701,
    lng: -104.8493,
    src: CREW_MARKER_SRC,
    label: "KAPA · Castle Rock / Denver South Crew Coverage",
    airportCode: "KAPA",
    airportName: "Centennial Airport",
    sourceLocation: "Castle Rock, CO",
    crewCount: 1,
  },
  {
    lat: 32.7338,
    lng: -117.1933,
    src: CREW_MARKER_SRC,
    label: "KSAN · San Diego Crew Coverage",
    airportCode: "KSAN",
    airportName: "San Diego International Airport",
    sourceLocation: "San Diego, CA",
    crewCount: 1,
  },
  {
    lat: 42.7817,
    lng: -71.5148,
    src: CREW_MARKER_SRC,
    label: "KASH · Southern New Hampshire Crew Coverage",
    airportCode: "KASH",
    airportName: "Nashua Airport",
    sourceLocation: "Wilton, NH",
    crewCount: 1,
  },
  {
    lat: 42.2379,
    lng: -83.5304,
    src: CREW_MARKER_SRC,
    label: "KYIP · Ypsilanti Crew Coverage",
    airportCode: "KYIP",
    airportName: "Willow Run Airport",
    sourceLocation: "Ypsilanti, MI",
    crewCount: 1,
  },
  {
    lat: 28.5455,
    lng: -81.3329,
    src: CREW_MARKER_SRC,
    label: "KORL · Orlando Crew Coverage",
    airportCode: "KORL",
    airportName: "Orlando Executive Airport",
    sourceLocation: "Orlando, FL",
    crewCount: 1,
  },
  {
    lat: 38.7487,
    lng: -90.37,
    src: CREW_MARKER_SRC,
    label: "KSTL · St. Louis Crew Coverage",
    airportCode: "KSTL",
    airportName: "St. Louis Lambert International Airport",
    sourceLocation: "Kirkwood, MO",
    crewCount: 1,
  },
  {
    lat: 36.0051,
    lng: -94.1701,
    src: CREW_MARKER_SRC,
    label: "KFYV · Northwest Arkansas Crew Coverage",
    airportCode: "KFYV",
    airportName: "Drake Field",
    sourceLocation: "West Fork, AR",
    crewCount: 1,
  },
  {
    lat: 40.6521,
    lng: -75.4408,
    src: CREW_MARKER_SRC,
    label: "KABE · Lehigh Valley Crew Coverage",
    airportCode: "KABE",
    airportName: "Lehigh Valley International Airport",
    sourceLocation: "Allentown, PA",
    crewCount: 1,
  },
  {
    lat: 42.5571,
    lng: -92.4003,
    src: CREW_MARKER_SRC,
    label: "KALO · Waterloo Crew Coverage",
    airportCode: "KALO",
    airportName: "Waterloo Regional Airport",
    sourceLocation: "Waterloo, IA",
    crewCount: 1,
  },
  {
    lat: 26.5866,
    lng: -81.8633,
    src: CREW_MARKER_SRC,
    label: "KFMY · Cape Coral / Fort Myers Crew Coverage",
    airportCode: "KFMY",
    airportName: "Page Field",
    sourceLocation: "Cape Coral, FL",
    crewCount: 1,
  },
  {
    lat: 26.9202,
    lng: -81.9905,
    src: CREW_MARKER_SRC,
    label: "KPGD · Punta Gorda Crew Coverage",
    airportCode: "KPGD",
    airportName: "Punta Gorda Airport",
    sourceLocation: "Punta Gorda, FL",
    crewCount: 1,
  },
  {
    lat: 43.2027,
    lng: -71.5023,
    src: CREW_MARKER_SRC,
    label: "KCON · Central New Hampshire Crew Coverage",
    airportCode: "KCON",
    airportName: "Concord Municipal Airport",
    sourceLocation: "Deerfield, NH",
    crewCount: 1,
  },
  {
    lat: 27.9767,
    lng: -82.7587,
    src: CREW_MARKER_SRC,
    label: "KCLW · Clearwater / Belleair Crew Coverage",
    airportCode: "KCLW",
    airportName: "Clearwater Air Park",
    sourceLocation: "Belleair Beach, FL",
    crewCount: 1,
  },
  {
    lat: 32.2244,
    lng: -80.6975,
    src: CREW_MARKER_SRC,
    label: "KHXD · Hilton Head Crew Coverage",
    airportCode: "KHXD",
    airportName: "Hilton Head Airport",
    sourceLocation: "Hilton Head, SC",
    crewCount: 1,
  },
  {
    lat: 40.3544,
    lng: -79.9302,
    src: CREW_MARKER_SRC,
    label: "KAGC · Pittsburgh Crew Coverage",
    airportCode: "KAGC",
    airportName: "Allegheny County Airport",
    sourceLocation: "Pittsburgh, PA",
    crewCount: 1,
  },
  {
    lat: 35.5342,
    lng: -97.6471,
    src: CREW_MARKER_SRC,
    label: "KPWA · Oklahoma City / Yukon Crew Coverage",
    airportCode: "KPWA",
    airportName: "Wiley Post Airport",
    sourceLocation: "Yukon, OK",
    crewCount: 1,
  },
  {
    lat: 46.9207,
    lng: -96.8158,
    src: CREW_MARKER_SRC,
    label: "KFAR · Fargo Crew Coverage",
    airportCode: "KFAR",
    airportName: "Hector International Airport",
    sourceLocation: "Fargo, ND",
    crewCount: 1,
  },
  {
    lat: 30.0618,
    lng: -95.5528,
    src: CREW_MARKER_SRC,
    label: "KDWH · North Houston Crew Coverage · 2",
    airportCode: "KDWH",
    airportName: "David Wayne Hooks Memorial Airport",
    sourceLocation: "Cypress, TX / Spring, TX",
    crewCount: 2,
  },
  {
    lat: 38.5452,
    lng: -89.8352,
    src: CREW_MARKER_SRC,
    label: "KBLV · Metro East / O'Fallon Crew Coverage",
    airportCode: "KBLV",
    airportName: "MidAmerica St. Louis Airport",
    sourceLocation: "O'Fallon, IL",
    crewCount: 1,
  },
  {
    lat: 33.6757,
    lng: -117.8682,
    src: CREW_MARKER_SRC,
    label: "KSNA · Orange County Crew Coverage",
    airportCode: "KSNA",
    airportName: "John Wayne Airport",
    sourceLocation: "Lake Forest, CA",
    crewCount: 1,
  },
  {
    lat: 38.9445,
    lng: -77.4558,
    src: CREW_MARKER_SRC,
    label: "KIAD · Northern Virginia Crew Coverage",
    airportCode: "KIAD",
    airportName: "Washington Dulles International Airport",
    sourceLocation: "Sterling, VA",
    crewCount: 1,
  },
  {
    lat: 33.4343,
    lng: -112.0116,
    src: CREW_MARKER_SRC,
    label: "KPHX · Phoenix / Tempe Crew Coverage",
    airportCode: "KPHX",
    airportName: "Phoenix Sky Harbor International Airport",
    sourceLocation: "Tempe, AZ",
    crewCount: 1,
  },
  {
    lat: 42.3742,
    lng: -122.8735,
    src: CREW_MARKER_SRC,
    label: "KMFR · Southern Oregon Crew Coverage",
    airportCode: "KMFR",
    airportName: "Rogue Valley International-Medford Airport",
    sourceLocation: "Central Point, OR",
    crewCount: 1,
  },
  {
    lat: 29.0669,
    lng: -81.2838,
    src: CREW_MARKER_SRC,
    label: "KDED · DeLand Crew Coverage",
    airportCode: "KDED",
    airportName: "DeLand Municipal Airport",
    sourceLocation: "DeLand, FL",
    crewCount: 1,
  },
  {
    lat: 33.1779,
    lng: -96.5905,
    src: CREW_MARKER_SRC,
    label: "KTKI · North Dallas / Princeton Crew Coverage",
    airportCode: "KTKI",
    airportName: "McKinney National Airport",
    sourceLocation: "Princeton, TX",
    crewCount: 1,
  },
  {
    lat: 29.9934,
    lng: -90.258,
    src: CREW_MARKER_SRC,
    label: "KMSY · New Orleans / Kenner Crew Coverage",
    airportCode: "KMSY",
    airportName: "Louis Armstrong New Orleans International Airport",
    sourceLocation: "Kenner, LA",
    crewCount: 1,
  },
  {
    lat: 32.8471,
    lng: -96.8518,
    src: CREW_MARKER_SRC,
    label: "KDAL · Dallas Crew Coverage",
    airportCode: "KDAL",
    airportName: "Dallas Love Field",
    sourceLocation: "Dallas, TX",
    crewCount: 1,
  },
  {
    lat: 40.3092,
    lng: -81.8533,
    src: CREW_MARKER_SRC,
    label: "I40 · East-Central Ohio Crew Coverage",
    airportCode: "I40",
    airportName: "Richard Downing Airport",
    sourceLocation: "Walhonding, OH",
    crewCount: 1,
  },
];

export const crewAirportMarkerStats = {
  publicMarkerCount: crewAirportGlobeMarkers.length,
  publicCrewCount: crewAirportGlobeMarkers.reduce((total, marker) => total + marker.crewCount, 0),
  excludedLocationReviewNeededCount: 9,
};
