import type { GlobeMarker } from "@/components/ui/3d-globe";

export type CrewAirportCoverageMarker = GlobeMarker & {
  airportCode: string;
  airportName: string;
  sourceLocation: string;
  crewCount: number;
};

const CREW_MARKER_SRC = "/images/flightdeck/crew-marker.svg";

export const crewAirportGlobeMarkers: CrewAirportCoverageMarker[] = [
{
    lat: 33.5629,
    lng: -86.7535,
    src: CREW_MARKER_SRC,
    label: "KBHM · Birmingham Crew Coverage",
    airportCode: "KBHM",
    airportName: "Birmingham-Shuttlesworth International Airport",
    sourceLocation: "Birmingham, AL",
    crewCount: 1,
  },
  {
    lat: 33.6229,
    lng: -111.9105,
    src: CREW_MARKER_SRC,
    label: "KSDL · Scottsdale / Phoenix Crew Coverage",
    airportCode: "KSDL",
    airportName: "Scottsdale Airport",
    sourceLocation: "Scottsdale, AZ",
    crewCount: 1,
  },
  {
    lat: 34.7294,
    lng: -92.2243,
    src: CREW_MARKER_SRC,
    label: "KLIT · Little Rock Crew Coverage",
    airportCode: "KLIT",
    airportName: "Bill and Hillary Clinton National Airport",
    sourceLocation: "Little Rock, AR",
    crewCount: 1,
  },
  {
    lat: 34.2098,
    lng: -118.4899,
    src: CREW_MARKER_SRC,
    label: "KVNY · Los Angeles / Van Nuys Crew Coverage",
    airportCode: "KVNY",
    airportName: "Van Nuys Airport",
    sourceLocation: "Van Nuys, CA",
    crewCount: 1,
  },
  {
    lat: 39.5701,
    lng: -104.8493,
    src: CREW_MARKER_SRC,
    label: "KAPA · Denver South Crew Coverage",
    airportCode: "KAPA",
    airportName: "Centennial Airport",
    sourceLocation: "Denver / Centennial, CO",
    crewCount: 1,
  },
  {
    lat: 41.9389,
    lng: -72.6832,
    src: CREW_MARKER_SRC,
    label: "KBDL · Hartford Crew Coverage",
    airportCode: "KBDL",
    airportName: "Bradley International Airport",
    sourceLocation: "Hartford, CT",
    crewCount: 1,
  },
  {
    lat: 39.6787,
    lng: -75.6065,
    src: CREW_MARKER_SRC,
    label: "KILG · Wilmington Crew Coverage",
    airportCode: "KILG",
    airportName: "Wilmington Airport",
    sourceLocation: "Wilmington, DE",
    crewCount: 1,
  },
  {
    lat: 26.2471,
    lng: -80.1111,
    src: CREW_MARKER_SRC,
    label: "KPMP · South Florida Crew Coverage",
    airportCode: "KPMP",
    airportName: "Pompano Beach Airpark",
    sourceLocation: "Pompano Beach, FL",
    crewCount: 1,
  },
  {
    lat: 33.8756,
    lng: -84.3020,
    src: CREW_MARKER_SRC,
    label: "KPDK · Atlanta Crew Coverage",
    airportCode: "KPDK",
    airportName: "DeKalb-Peachtree Airport",
    sourceLocation: "Atlanta, GA",
    crewCount: 1,
  },
  {
    lat: 43.5644,
    lng: -116.2228,
    src: CREW_MARKER_SRC,
    label: "KBOI · Boise Crew Coverage",
    airportCode: "KBOI",
    airportName: "Boise Airport",
    sourceLocation: "Boise, ID",
    crewCount: 1,
  },
  {
    lat: 42.1143,
    lng: -87.9015,
    src: CREW_MARKER_SRC,
    label: "KPWK · Chicago Executive Crew Coverage",
    airportCode: "KPWK",
    airportName: "Chicago Executive Airport",
    sourceLocation: "Chicago, IL",
    crewCount: 1,
  },
  {
    lat: 39.7173,
    lng: -86.2944,
    src: CREW_MARKER_SRC,
    label: "KIND · Indianapolis Crew Coverage",
    airportCode: "KIND",
    airportName: "Indianapolis International Airport",
    sourceLocation: "Indianapolis, IN",
    crewCount: 1,
  },
  {
    lat: 41.5340,
    lng: -93.6631,
    src: CREW_MARKER_SRC,
    label: "KDSM · Des Moines Crew Coverage",
    airportCode: "KDSM",
    airportName: "Des Moines International Airport",
    sourceLocation: "Des Moines, IA",
    crewCount: 1,
  },
  {
    lat: 37.6499,
    lng: -97.4331,
    src: CREW_MARKER_SRC,
    label: "KICT · Wichita Crew Coverage",
    airportCode: "KICT",
    airportName: "Wichita Dwight D. Eisenhower National Airport",
    sourceLocation: "Wichita, KS",
    crewCount: 1,
  },
  {
    lat: 38.2280,
    lng: -85.6637,
    src: CREW_MARKER_SRC,
    label: "KLOU · Louisville Crew Coverage",
    airportCode: "KLOU",
    airportName: "Bowman Field",
    sourceLocation: "Louisville, KY",
    crewCount: 1,
  },
  {
    lat: 30.0424,
    lng: -90.0283,
    src: CREW_MARKER_SRC,
    label: "KNEW · New Orleans Crew Coverage",
    airportCode: "KNEW",
    airportName: "Lakefront Airport",
    sourceLocation: "New Orleans, LA",
    crewCount: 1,
  },
  {
    lat: 43.6462,
    lng: -70.3093,
    src: CREW_MARKER_SRC,
    label: "KPWM · Portland Maine Crew Coverage",
    airportCode: "KPWM",
    airportName: "Portland International Jetport",
    sourceLocation: "Portland, ME",
    crewCount: 1,
  },
  {
    lat: 39.3257,
    lng: -76.4138,
    src: CREW_MARKER_SRC,
    label: "KMTN · Baltimore / Martin State Crew Coverage",
    airportCode: "KMTN",
    airportName: "Martin State Airport",
    sourceLocation: "Baltimore, MD",
    crewCount: 1,
  },
  {
    lat: 42.4700,
    lng: -71.2890,
    src: CREW_MARKER_SRC,
    label: "KBED · Boston / Hanscom Crew Coverage",
    airportCode: "KBED",
    airportName: "Laurence G. Hanscom Field",
    sourceLocation: "Bedford, MA",
    crewCount: 1,
  },
  {
    lat: 42.8808,
    lng: -85.5228,
    src: CREW_MARKER_SRC,
    label: "KGRR · Grand Rapids Crew Coverage",
    airportCode: "KGRR",
    airportName: "Gerald R. Ford International Airport",
    sourceLocation: "Grand Rapids, MI",
    crewCount: 1,
  },
  {
    lat: 44.8272,
    lng: -93.4571,
    src: CREW_MARKER_SRC,
    label: "KFCM · Minneapolis / Flying Cloud Crew Coverage",
    airportCode: "KFCM",
    airportName: "Flying Cloud Airport",
    sourceLocation: "Minneapolis, MN",
    crewCount: 1,
  },
  {
    lat: 32.3112,
    lng: -90.0759,
    src: CREW_MARKER_SRC,
    label: "KJAN · Jackson Crew Coverage",
    airportCode: "KJAN",
    airportName: "Jackson-Medgar Wiley Evers International Airport",
    sourceLocation: "Jackson, MS",
    crewCount: 1,
  },
  {
    lat: 38.6621,
    lng: -90.6520,
    src: CREW_MARKER_SRC,
    label: "KSUS · St. Louis / Spirit Crew Coverage",
    airportCode: "KSUS",
    airportName: "Spirit of St. Louis Airport",
    sourceLocation: "St. Louis, MO",
    crewCount: 1,
  },
  {
    lat: 45.7775,
    lng: -111.1530,
    src: CREW_MARKER_SRC,
    label: "KBZN · Bozeman Crew Coverage",
    airportCode: "KBZN",
    airportName: "Bozeman Yellowstone International Airport",
    sourceLocation: "Bozeman, MT",
    crewCount: 1,
  },
  {
    lat: 41.3032,
    lng: -95.8941,
    src: CREW_MARKER_SRC,
    label: "KOMA · Omaha Crew Coverage",
    airportCode: "KOMA",
    airportName: "Eppley Airfield",
    sourceLocation: "Omaha, NE",
    crewCount: 1,
  },
  {
    lat: 35.9728,
    lng: -115.1344,
    src: CREW_MARKER_SRC,
    label: "KHND · Las Vegas / Henderson Crew Coverage",
    airportCode: "KHND",
    airportName: "Henderson Executive Airport",
    sourceLocation: "Henderson, NV",
    crewCount: 1,
  },
  {
    lat: 42.7817,
    lng: -71.5148,
    src: CREW_MARKER_SRC,
    label: "KASH · Southern New Hampshire Crew Coverage",
    airportCode: "KASH",
    airportName: "Nashua Airport",
    sourceLocation: "Nashua, NH",
    crewCount: 1,
  },
  {
    lat: 40.8501,
    lng: -74.0608,
    src: CREW_MARKER_SRC,
    label: "KTEB · Teterboro / New York Metro Crew Coverage",
    airportCode: "KTEB",
    airportName: "Teterboro Airport",
    sourceLocation: "Teterboro, NJ",
    crewCount: 1,
  },
  {
    lat: 35.0402,
    lng: -106.6090,
    src: CREW_MARKER_SRC,
    label: "KABQ · Albuquerque Crew Coverage",
    airportCode: "KABQ",
    airportName: "Albuquerque International Sunport",
    sourceLocation: "Albuquerque, NM",
    crewCount: 1,
  },
  {
    lat: 41.0669,
    lng: -73.7076,
    src: CREW_MARKER_SRC,
    label: "KHPN · Westchester / New York Crew Coverage",
    airportCode: "KHPN",
    airportName: "Westchester County Airport",
    sourceLocation: "White Plains, NY",
    crewCount: 1,
  },
  {
    lat: 35.8776,
    lng: -78.7875,
    src: CREW_MARKER_SRC,
    label: "KRDU · Raleigh-Durham Crew Coverage",
    airportCode: "KRDU",
    airportName: "Raleigh-Durham International Airport",
    sourceLocation: "Raleigh-Durham, NC",
    crewCount: 1,
  },
  {
    lat: 46.9207,
    lng: -96.8158,
    src: CREW_MARKER_SRC,
    label: "KFAR · Fargo Crew Coverage",
    airportCode: "KFAR",
    airportName: "Hector International Airport",
    sourceLocation: "Fargo, ND",
    crewCount: 1,
  },
  {
    lat: 39.9980,
    lng: -82.8919,
    src: CREW_MARKER_SRC,
    label: "KCMH · Columbus Crew Coverage",
    airportCode: "KCMH",
    airportName: "John Glenn Columbus International Airport",
    sourceLocation: "Columbus, OH",
    crewCount: 1,
  },
  {
    lat: 35.5342,
    lng: -97.6471,
    src: CREW_MARKER_SRC,
    label: "KPWA · Oklahoma City Crew Coverage",
    airportCode: "KPWA",
    airportName: "Wiley Post Airport",
    sourceLocation: "Oklahoma City, OK",
    crewCount: 1,
  },
  {
    lat: 45.5404,
    lng: -122.9498,
    src: CREW_MARKER_SRC,
    label: "KHIO · Portland / Hillsboro Crew Coverage",
    airportCode: "KHIO",
    airportName: "Hillsboro Airport",
    sourceLocation: "Hillsboro, OR",
    crewCount: 1,
  },
  {
    lat: 40.3544,
    lng: -79.9302,
    src: CREW_MARKER_SRC,
    label: "KAGC · Pittsburgh Crew Coverage",
    airportCode: "KAGC",
    airportName: "Allegheny County Airport",
    sourceLocation: "Pittsburgh, PA",
    crewCount: 1,
  },
  {
    lat: 41.7240,
    lng: -71.4282,
    src: CREW_MARKER_SRC,
    label: "KPVD · Providence Crew Coverage",
    airportCode: "KPVD",
    airportName: "Rhode Island T. F. Green International Airport",
    sourceLocation: "Providence, RI",
    crewCount: 1,
  },
  {
    lat: 32.8986,
    lng: -80.0405,
    src: CREW_MARKER_SRC,
    label: "KCHS · Charleston Crew Coverage",
    airportCode: "KCHS",
    airportName: "Charleston International Airport",
    sourceLocation: "Charleston, SC",
    crewCount: 1,
  },
  {
    lat: 43.5820,
    lng: -96.7419,
    src: CREW_MARKER_SRC,
    label: "KFSD · Sioux Falls Crew Coverage",
    airportCode: "KFSD",
    airportName: "Sioux Falls Regional Airport",
    sourceLocation: "Sioux Falls, SD",
    crewCount: 1,
  },
  {
    lat: 36.1245,
    lng: -86.6782,
    src: CREW_MARKER_SRC,
    label: "KBNA · Nashville Crew Coverage",
    airportCode: "KBNA",
    airportName: "Nashville International Airport",
    sourceLocation: "Nashville, TN",
    crewCount: 1,
  },
  {
    lat: 32.8471,
    lng: -96.8518,
    src: CREW_MARKER_SRC,
    label: "KDAL · Dallas Crew Coverage",
    airportCode: "KDAL",
    airportName: "Dallas Love Field",
    sourceLocation: "Dallas, TX",
    crewCount: 1,
  },
  {
    lat: 40.7884,
    lng: -111.9778,
    src: CREW_MARKER_SRC,
    label: "KSLC · Salt Lake City Crew Coverage",
    airportCode: "KSLC",
    airportName: "Salt Lake City International Airport",
    sourceLocation: "Salt Lake City, UT",
    crewCount: 1,
  },
  {
    lat: 44.4719,
    lng: -73.1533,
    src: CREW_MARKER_SRC,
    label: "KBTV · Burlington Crew Coverage",
    airportCode: "KBTV",
    airportName: "Patrick Leahy Burlington International Airport",
    sourceLocation: "Burlington, VT",
    crewCount: 1,
  },
  {
    lat: 38.9445,
    lng: -77.4558,
    src: CREW_MARKER_SRC,
    label: "KIAD · Northern Virginia / Dulles Crew Coverage",
    airportCode: "KIAD",
    airportName: "Washington Dulles International Airport",
    sourceLocation: "Dulles, VA",
    crewCount: 1,
  },
  {
    lat: 47.5299,
    lng: -122.3019,
    src: CREW_MARKER_SRC,
    label: "KBFI · Seattle / Boeing Field Crew Coverage",
    airportCode: "KBFI",
    airportName: "Boeing Field / King County International Airport",
    sourceLocation: "Seattle, WA",
    crewCount: 1,
  },
  {
    lat: 38.3731,
    lng: -81.5932,
    src: CREW_MARKER_SRC,
    label: "KCRW · Charleston West Virginia Crew Coverage",
    airportCode: "KCRW",
    airportName: "West Virginia International Yeager Airport",
    sourceLocation: "Charleston, WV",
    crewCount: 1,
  },
  {
    lat: 43.1399,
    lng: -89.3375,
    src: CREW_MARKER_SRC,
    label: "KMSN · Madison Crew Coverage",
    airportCode: "KMSN",
    airportName: "Dane County Regional Airport",
    sourceLocation: "Madison, WI",
    crewCount: 1,
  },
  {
    lat: 41.1557,
    lng: -104.8118,
    src: CREW_MARKER_SRC,
    label: "KCYS · Cheyenne Crew Coverage",
    airportCode: "KCYS",
    airportName: "Cheyenne Regional Airport",
    sourceLocation: "Cheyenne, WY",
    crewCount: 1,
  },
];

export const crewAirportMarkerStats = {
  publicMarkerCount: crewAirportGlobeMarkers.length,
  publicCrewCount: crewAirportGlobeMarkers.reduce((total, marker) => total + marker.crewCount, 0),
  excludedLocationReviewNeededCount: 9,
};
