import { createHash } from "crypto";

export const FORE_FLIGHT_MAX_BYTES = 10 * 1024 * 1024;
export const PARSER_VERSION = "foreflight-csv-v1";
type Row = Record<string, string>;
export type Entry = { sourceRowNumber: number; fingerprint: string; sourceRow: Row; flightDate: string | null; aircraftIdentifier: string | null; aircraftType: string | null; fromAirport: string | null; toAirport: string | null; totalTime: number | null; picTime: number | null; sicTime: number | null; dualReceivedTime: number | null; soloTime: number | null; crossCountryTime: number | null; nightTime: number | null; actualInstrumentTime: number | null; simulatedInstrumentTime: number | null; dayLandings: number | null; nightLandings: number | null; approachesCount: number | null; holdsCount: number | null; route: string | null; remarks: string | null };
export type RowIssue = { row: number; field?: string; message: string };
const aliases: Record<string, string[]> = { date:["date","flight date"], aircraftIdentifier:["aircraft id","aircraft","tail number","registration"], aircraftType:["aircraft type","type"], fromAirport:["from","departure"], toAirport:["to","arrival"], totalTime:["total time","total"], picTime:["pic","pic time"], sicTime:["sic","sic time"], dualReceivedTime:["dual received","dual"], soloTime:["solo"], crossCountryTime:["cross country","cross-country","xc"], nightTime:["night"], actualInstrumentTime:["actual instrument","actual"], simulatedInstrumentTime:["simulated instrument","sim instrument","simulated"], dayLandings:["day landings","day landing"], nightLandings:["night landings","night landing"], approachesCount:["approaches","approach count"], holdsCount:["holds","hold count"], route:["route"], remarks:["remarks","comments","notes"] };
function csv(text:string): string[][] { const rows:string[][]=[]; let row:string[]=[], value="", quote=false; for(let i=0;i<text.length;i++){const c=text[i], n=text[i+1]; if(c==='"'){if(quote&&n==='"'){value+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(value);value="";}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(value); if(row.some(v=>v.trim()))rows.push(row); row=[];value="";}else value+=c;} if(quote) throw new Error("Unterminated quoted CSV field."); if(value||row.length){row.push(value);rows.push(row);} return rows; }
function norm(v:string){return v.trim().toLowerCase().replace(/^\ufeff/,"").replace(/\s+/g," ");}
function column(headers:string[], key:string){return headers.findIndex(h=>aliases[key].includes(norm(h)));}
function nullable(v:string|undefined){const x=v?.trim()??""; return x||null;}
function numberValue(v:string|undefined, row:number, field:string, issues:RowIssue[], integer=false){const x=nullable(v); if(x===null)return null; if(!/^\d+(\.\d{1,2})?$/.test(x)){issues.push({row,field,message:"Must be a non-negative number with at most two decimals."});return null;} const n=Number(x); if(integer&&!Number.isInteger(n)){issues.push({row,field,message:"Must be a whole number."});return null;} return n;}
function dateValue(v:string|undefined,row:number,issues:RowIssue[]){const x=nullable(v);if(!x)return null; const d=new Date(`${x}T00:00:00Z`);if(Number.isNaN(d.valueOf())){issues.push({row,field:"Date",message:"Invalid flight date."});return null;}return d.toISOString().slice(0,10);}
export function fingerprint(entry:Omit<Entry,"fingerprint">){const canonical=JSON.stringify({d:entry.flightDate,a:entry.aircraftIdentifier?.toUpperCase()??null,t:entry.aircraftType?.toUpperCase()??null,f:entry.fromAirport?.toUpperCase()??null,to:entry.toAirport?.toUpperCase()??null,total:entry.totalTime,pic:entry.picTime,sic:entry.sicTime,dual:entry.dualReceivedTime,solo:entry.soloTime,xc:entry.crossCountryTime,night:entry.nightTime,actual:entry.actualInstrumentTime,sim:entry.simulatedInstrumentTime,dl:entry.dayLandings,nl:entry.nightLandings,ap:entry.approachesCount,holds:entry.holdsCount,route:entry.route,remarks:entry.remarks});return createHash("sha256").update(canonical).digest("hex");}
export function parseForeFlightCsv(text:string){if(text.length>FORE_FLIGHT_MAX_BYTES) throw new Error("CSV exceeds the 10 MB limit."); const rows=csv(text); if(rows.length<2)throw new Error("CSV must include a header and at least one data row.");const headers=rows[0].map(h=>h.trim()); const idx=Object.fromEntries(Object.keys(aliases).map(k=>[k,column(headers,k)]));for(const key of ["date","aircraftIdentifier","totalTime"]){if(idx[key]<0)throw new Error(`Unsupported CSV: required ForeFlight column '${aliases[key][0]}' is missing.`);}const entries:Entry[]=[],issues:RowIssue[]=[];for(let r=1;r<rows.length;r++){const raw=Object.fromEntries(headers.map((h,i)=>[h,rows[r][i]??""]));const row=r+1;const local:RowIssue[]=[];const get=(k:string)=>idx[k]>=0?rows[r][idx[k]]:undefined;const base={sourceRowNumber:row,sourceRow:raw,flightDate:dateValue(get("date"),row,local),aircraftIdentifier:nullable(get("aircraftIdentifier")),aircraftType:nullable(get("aircraftType")),fromAirport:nullable(get("fromAirport")),toAirport:nullable(get("toAirport")),totalTime:numberValue(get("totalTime"),row,"Total Time",local),picTime:numberValue(get("picTime"),row,"PIC",local),sicTime:numberValue(get("sicTime"),row,"SIC",local),dualReceivedTime:numberValue(get("dualReceivedTime"),row,"Dual Received",local),soloTime:numberValue(get("soloTime"),row,"Solo",local),crossCountryTime:numberValue(get("crossCountryTime"),row,"Cross Country",local),nightTime:numberValue(get("nightTime"),row,"Night",local),actualInstrumentTime:numberValue(get("actualInstrumentTime"),row,"Actual Instrument",local),simulatedInstrumentTime:numberValue(get("simulatedInstrumentTime"),row,"Simulated Instrument",local),dayLandings:numberValue(get("dayLandings"),row,"Day Landings",local,true),nightLandings:numberValue(get("nightLandings"),row,"Night Landings",local,true),approachesCount:numberValue(get("approachesCount"),row,"Approaches",local,true),holdsCount:numberValue(get("holdsCount"),row,"Holds",local,true),route:nullable(get("route")),remarks:nullable(get("remarks"))};if(!base.flightDate)local.push({row,field:"Date",message:"Flight date is required."});if(!base.aircraftIdentifier)local.push({row,field:"Aircraft ID",message:"Aircraft identifier is required."});if(base.totalTime===null)local.push({row,field:"Total Time",message:"Total time is required."});issues.push(...local);if(!local.length)entries.push({...base,fingerprint:fingerprint(base)});}return {headers,totalRows:rows.length-1,entries,issues};}
export type Finding={severity:"hard_error"|"review_warning";ruleCode:string;explanation:string;recommendedCorrection:string;sourceRowNumber:number;evidence:Record<string,unknown>};
export function audit(entry:Entry):Finding[]{const f:Finding[]=[];const add=(severity:Finding["severity"],ruleCode:string,explanation:string,recommendedCorrection:string)=>f.push({severity,ruleCode,explanation,recommendedCorrection,sourceRowNumber:entry.sourceRowNumber,evidence:{total_time:entry.totalTime,pic:entry.picTime,sic:entry.sicTime,aircraft:entry.aircraftIdentifier}});const total=entry.totalTime??0;for(const [name,v] of Object.entries({PIC:entry.picTime,SIC:entry.sicTime,"Dual received":entry.dualReceivedTime,Solo:entry.soloTime,"Cross-country":entry.crossCountryTime,Night:entry.nightTime,"Actual instrument":entry.actualInstrumentTime,"Simulated instrument":entry.simulatedInstrumentTime})){if(v!==null&&v>total)add("hard_error","SUBCATEGORY_EXCEEDS_TOTAL",`${name} time exceeds total flight time.`,"Confirm the source time columns and correct the logbook entry in ForeFlight.");}if((entry.picTime??0)+(entry.sicTime??0)>total)add("review_warning","PIC_SIC_EXCEEDS_TOTAL","PIC plus SIC exceeds total time.","Confirm whether overlapping credit is intentional and retain supporting documentation.");if((entry.dualReceivedTime??0)>0&&(entry.soloTime??0)>0)add("review_warning","DUAL_SOLO_CONTRADICTION","Dual received and solo are both recorded on one flight.","Review the lesson/solo designation in ForeFlight.");if((entry.actualInstrumentTime??0)+(entry.simulatedInstrumentTime??0)>total)add("review_warning","INSTRUMENT_EXCEEDS_TOTAL","Actual plus simulated instrument exceeds total time.","Review instrument fields; some simulator time may need separate treatment.");if(!entry.aircraftIdentifier)add("hard_error","MISSING_AIRCRAFT","No aircraft identifier is present.","Add the registration or other aircraft identifier in ForeFlight.");return f;}
