import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle2,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Eye,
  FileText,
  Gauge,
  Globe2,
  Handshake,
  History,
  Inbox,
  Layers,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  Pencil,
  Phone,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Plus,
  Radar,
  Receipt,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  Users,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertTriangle,
  archive: Archive,
  arrowUpRight: ArrowUpRight,
  badgeCheck: BadgeCheck,
  barChart: BarChart3,
  bell: Bell,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  check: CheckCircle2,
  clipboard: ClipboardList,
  clock: Clock,
  creditCard: CreditCard,
  dollar: DollarSign,
  download: Download,
  eye: Eye,
  fileText: FileText,
  gauge: Gauge,
  globe: Globe2,
  handshake: Handshake,
  history: History,
  inbox: Inbox,
  layers: Layers,
  logout: LogOut,
  mail: Mail,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  pencil: Pencil,
  phone: Phone,
  plane: Plane,
  planeLanding: PlaneLanding,
  planeTakeoff: PlaneTakeoff,
  plus: Plus,
  radar: Radar,
  receipt: Receipt,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  trendingUp: TrendingUp,
  upload: Upload,
  user: User,
  userCheck: UserCheck,
  users: Users,
  wallet: Wallet,
  wrench: Wrench,
  zap: Zap,
};

export function PortalIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Gauge;
  return <Icon className={className} />;
}
